// Build step (`npm run build:dist`, the last stage of `npm run build`): emit a
// self-contained `dist/index.js` from the `src/index.js` manifest.
//
// Every coreutil bundle (built by tools/bundle.mjs into src/bundles/) is read at
// build time and inlined as a JS string, so the published module needs no runtime
// `import.meta.url` fetch. A consumer imports `@opentf/workeros-coreutils` by name
// and its bundler carries the whole /sbin program set — no raw serving, no
// sibling-tree layout. Mirrors packages/workeros-programs/tools/build-dist.mjs.
import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { bundledCoreutils } from "../src/index.js";

const srcDir = fileURLToPath(new URL("../src", import.meta.url));
const distDir = fileURLToPath(new URL("../dist", import.meta.url));
const resolve = (file) => join(srcDir, file.replace(/^\.\//, ""));

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });

const TEXT = {};
for (const { file } of bundledCoreutils) TEXT[file] = await readFile(resolve(file), "utf8");

const meta = bundledCoreutils.map(({ path, file }) => ({ path, file }));

const out = `// GENERATED by tools/build-dist.mjs — do not edit. Source of truth: src/index.js.
// Self-contained: every coreutil bundle is inlined, so the package is consumed by
// name with no runtime fetch.

const TEXT = ${JSON.stringify(TEXT)};

export const bundledCoreutils = ${JSON.stringify(meta, null, 2)}
  .map((c) => ({ ...c, source: () => Promise.resolve(TEXT[c.file]) }));
`;

await writeFile(join(distDir, "index.js"), out);
console.log(`[build-dist] wrote dist/index.js (${meta.length} coreutils inlined)`);
