// Build step (`npm run build:dist`, the last stage of `npm run build`): emit a
// self-contained `dist/index.js` from the `src/index.js` manifest.
//
// The manifest names, for every program and library, the relative `file` that
// holds its bytes. Here we read each of those files at build time and bake them
// into the published module so it needs no runtime `import.meta.url` fetch:
//
//   • text files  (program bundles, guest-lib sources) → inlined as JS strings.
//   • binary files (wasm images, the npm tarball)       → copied into dist/assets/
//     and referenced with `new URL("./assets/x", import.meta.url)`, the shape a
//     bundler (Vite/esbuild) statically recognises and emits as an asset.
//
// The result is `@opentf/workeros-programs` as a normal module: a consumer imports
// it by name, its bundler inlines the text and emits the wasm, and the whole OS
// program set travels with the bundle. No sibling-tree layout, no raw serving.
import { build } from "esbuild";
import { mkdir, readFile, writeFile, copyFile, rm } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import { programs, libraries } from "../src/index.js";

const srcDir = fileURLToPath(new URL("../src", import.meta.url));
const distDir = fileURLToPath(new URL("../dist", import.meta.url));
const assetsDir = join(distDir, "assets");

const resolve = (file) => join(srcDir, file.replace(/^\.\//, ""));
const isBinary = (file) => /\.(wasm|tgz)$/.test(file);

await rm(distDir, { recursive: true, force: true });
await mkdir(assetsDir, { recursive: true });

// Collect every distinct file the manifest references, classify text vs binary.
const files = [...new Set([...programs, ...libraries].map((e) => e.file))];
const textFiles = {}; // file -> source string
const assetKeys = {}; // file -> dist/assets/<name> basename (present only if the file exists)

for (const file of files) {
  if (isBinary(file)) {
    try {
      const name = basename(file);
      await copyFile(resolve(file), join(assetsDir, name));
      assetKeys[file] = name;
    } catch {
      // Optional binaries (codec.wasm, bundler.wasm, npm.tgz) may be absent when
      // the wasm/vendor build was skipped — the loader returns null for them.
    }
  } else {
    textFiles[file] = await readFile(resolve(file), "utf8");
  }
}

// Emit dist/index.js. `programs`/`libraries` keep the exact runtime shape the
// kernel worker consumes ({ bin/path, type, links?, source() }); only delivery
// changed (inlined content instead of a fetch).
const meta = (entries, kind) =>
  entries.map((e) => {
    const base = kind === "program"
      ? { bin: e.bin, type: e.type, file: e.file, ...(e.links ? { links: e.links } : {}) }
      : { path: e.path, file: e.file };
    return base;
  });

const out = `// GENERATED by tools/build-dist.mjs — do not edit. Source of truth: src/index.js.
// Self-contained: program/library text is inlined; wasm/tarball assets are emitted
// under ./assets and referenced by URL so a bundler ships them with the package.

const TEXT = ${JSON.stringify(textFiles)};

// Binary assets present at build time. \`new URL(..., import.meta.url)\` is the
// static form bundlers rewrite + emit; a missing key means the asset wasn't built.
const ASSET = {
${Object.entries(assetKeys)
  .map(([file, name]) => `  ${JSON.stringify(file)}: new URL(${JSON.stringify("./assets/" + name)}, import.meta.url),`)
  .join("\n")}
};

async function loadBinary(file) {
  const url = ASSET[file];
  if (!url) return null;
  try {
    const res = await fetch(url);
    return res.ok ? await res.arrayBuffer() : null;
  } catch {
    return null;
  }
}

const PROGRAMS = ${JSON.stringify(meta(programs, "program"), null, 2)};
const LIBRARIES = ${JSON.stringify(meta(libraries, "library"), null, 2)};

const loadFor = (file) =>
  file.endsWith(".wasm") || file.endsWith(".tgz")
    ? () => loadBinary(file)
    : () => Promise.resolve(TEXT[file]);

export const programs = PROGRAMS.map((p) => ({ ...p, source: loadFor(p.file) }));
export const libraries = LIBRARIES.map((l) => ({ ...l, source: loadFor(l.file) }));
`;

await writeFile(join(distDir, "index.js"), out);

// The host-side library subpaths (`@opentf/workeros-programs/node/process-shim`,
// `/wasi`) are pure code the program worker imports by name. Bundle them into dist
// so the package ships dist-only — no src tree, no duplicated wasm.
await build({
  entryPoints: {
    "node/process-shim": join(srcDir, "node/process-shim.js"),
    "wasi/host": join(srcDir, "wasi/host.js"),
  },
  outdir: distDir,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  legalComments: "none",
  logLevel: "warning",
});

console.log(
  `[build-dist] wrote dist/index.js (${Object.keys(textFiles).length} inlined, ` +
    `${Object.keys(assetKeys).length} assets) + subpath bundles`,
);
